var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/plan/route.js")
R.c("server/chunks/node_modules_@vercel_oidc_dist_7120b470._.js")
R.c("server/chunks/node_modules_next_dist_aab3aff5._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_zod_7a81769b._.js")
R.c("server/chunks/node_modules_@ai-sdk_google_dist_index_mjs_48543614._.js")
R.c("server/chunks/node_modules_ai_dist_index_mjs_b0116780._.js")
R.c("server/chunks/node_modules_3cf9dd36._.js")
R.c("server/chunks/[root-of-the-server]__1e05b9b3._.js")
R.c("server/chunks/_next-internal_server_app_api_plan_route_actions_f716c20d.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/plan/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/plan/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
